### ISSUE TITLE
Use absolute url for wix-storage strategy

### ISSUE THREAD

**Issue by liorcode** [wix/data-capsule#42]
For calls being made to `'/_api/wix-user-preferences-webap`, please use an absolute url (`https://www.wix.com/_api/wix-user-preferences-webap`)

Currently we have a problem that we configured axios's baseUrl configured to be something else, so data-capsule fails as it tries to reach our servers instead of the main wix.

**Comment by maxaon** [comment]
In https://github.com/wix/data-capsule/pull/43 agreed that this is not needed.
